apiVersion: batch/v1
kind: Job
metadata:
  name: hello-kubernetes-job
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never


