apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  completions: 8
  parallelism: 4
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "echo 'Executando tarefa'; sleep 30"]
      restartPolicy: Never



