apiVersion: batch/v1
kind: CronJob
metadata:
  name: custom-message-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 240
      template:
        spec:
          containers:
          - name: custom-message
            image: busybox
            command: ["sh", "-c", "echo 'This is a custom message'; sleep 30"]
          restartPolicy: Never


