apiVersion: batch/v1
kind: Job
metadata:
  name: paralelo-job
spec:
  completions: 5
  parallelism: 2
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: paralelo-job
        image: busybox
        command: ["sh", "-c", "echo 'Executando tarefa'; sleep 10"]
      restartPolicy: Never